- name: Query ServiceNow CMDB
  hosts: demo_hosts
  gather_facts: no

  tasks:
  - name: Get Azure token
    riotinto.servicenow.get_azure_token:
      tenant_id: "{{ sn_az_tenant_id }}"
      client_id: "{{ sn_az_client_id }}"
      client_secret: "{{ sn_az_client_secret }}"
      scope: "{{ sn_scope }}"
    register: token_result
    delegate_to: localhost
    run_once: true

  # - name: Show token
  #   debug:
  #     var: token_result.access_token

  - name: Get Azure Servers from cmdb_ci_server
    riotinto.servicenow.get_cmdb_records:
      instance_url: "{{ instance_url }}"
      auth_token: "{{ token_result.access_token }}"
      subscription_key: "{{ sn_subscription_key }}"
      table: "cmdb_ci_server"
      sysparm_query: "name={{ inventory_hostname }}"
      # sysparm_fields: "name,correlation_id,os,support_group&sysparm_display_value=true"
    register: cmdb_output
    delegate_to: localhost

  - name: Show output
    debug:
      var: cmdb_output.response
    delegate_to: localhost

  - name: set fact if server found
    set_stats:
      data:
        server_found: "{{ (cmdb_output.response.result | length > 0) | ternary(true, false) }}"
    delegate_to: localhost
    